'use client';
import {useMemo,useState} from 'react';

type Project={id:string;name:string;status:string;invested:number;income:number;expense:number;returned:number;fees:number;fiat:{asset:string;amount:number}[];crypto:{asset:string;amount:number;usd:number}[]};
const data:Project[]=[
{id:'dado',name:'Проект ДАДО',status:'ACTIVE',invested:125000,income:68400,expense:32100,returned:10000,fees:920,fiat:[{asset:'USD',amount:38500},{asset:'TJS',amount:245000}],crypto:[{asset:'USDT',amount:18200,usd:18200},{asset:'BTC',amount:.12,usd:0}]},
{id:'water',name:'Производство воды',status:'ACTIVE',invested:87000,income:41200,expense:28400,returned:0,fees:340,fiat:[{asset:'USD',amount:21800},{asset:'TJS',amount:97000}],crypto:[{asset:'USDT',amount:6500,usd:6500}]},
{id:'general',name:'Общие / вне проекта',status:'ACTIVE',invested:0,income:0,expense:7900,returned:0,fees:180,fiat:[{asset:'USD',amount:4200}],crypto:[]}
];
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function ProjectsPage(){const [selected,setSelected]=useState(data[0].id);const p=useMemo(()=>data.find(x=>x.id===selected)!,[selected]);const result=p.income+p.returned-p.expense-p.fees;return <main style={{minHeight:'100vh',background:'#090d14',color:'#e8edf5',padding:24,fontFamily:'Inter,Arial'}}><div style={{maxWidth:1250,margin:'auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><small style={{color:'#7f8b9c'}}>Финансы и инвестиция</small><h1>Проекты</h1></div><div><a href="/operations" style={{color:'#7aa7ff',marginRight:18}}>Операции</a><button style={btn}>+ Новый проект</button></div></header><div style={{display:'grid',gridTemplateColumns:'260px 1fr',gap:14}}><aside style={panel}><h3>Список проектов</h3>{data.map(x=><div key={x.id} onClick={()=>setSelected(x.id)} style={{padding:12,borderRadius:8,cursor:'pointer',background:selected===x.id?'#1a2638':'transparent',marginBottom:5}}><b>{x.name}</b><div style={{fontSize:11,color:'#35c98b',marginTop:4}}>{x.status}</div></div>)}</aside><section><div style={{...panel,marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h2 style={{marginTop:0}}>{p.name}</h2><span style={{color:'#7f8b9c'}}>Финансовая карточка проекта</span></div><button style={btn}>+ Операция проекта</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:8,marginTop:18}}><Card t="Вложено" v={money(p.invested)}/><Card t="Доход" v={money(p.income)} good/><Card t="Расход" v={money(p.expense)} bad/><Card t="Возвращено" v={money(p.returned)}/><Card t="Комиссии" v={money(p.fees)} bad/><Card t="Результат" v={money(result)} good={result>=0} bad={result<0}/></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><div style={panel}><h3>Фиатные средства</h3><Table rows={p.fiat.map(x=>[x.asset,x.amount.toLocaleString(),x.asset])}/></div><div style={panel}><h3>Криптовалюта</h3><Table rows={p.crypto.map(x=>[x.asset,x.amount.toLocaleString(),x.usd?money(x.usd):'по рынку'])}/></div></div><div style={{...panel,marginTop:14}}><h3>Структура результата</h3><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}><Card t="Операционный результат" v={money(p.income-p.expense-p.fees)} good/><Card t="Чистый денежный поток" v={money(result-p.invested)} bad={result-p.invested<0}/><Card t="Инвестировано" v={money(p.invested)}/><Card t="Доступно к возврату" v={money(Math.max(0,result))}/></div></div></section></div></div></main>}
const panel:React.CSSProperties={background:'#0f1622',border:'1px solid #202938',borderRadius:12,padding:16};const btn:React.CSSProperties={background:'#2b67f6',color:'#fff',border:0,borderRadius:8,padding:'10px 14px',fontWeight:700};
function Card({t,v,good,bad}:{t:string;v:string;good?:boolean;bad?:boolean}){return <div style={{background:'#0b111b',border:'1px solid #202938',borderRadius:9,padding:12}}><div style={{fontSize:11,color:'#7f8b9c'}}>{t}</div><b style={{display:'block',marginTop:7,color:good?'#35c98b':bad?'#ef6673':'#e8edf5'}}>{v}</b></div>}
function Table({rows}:{rows:string[][]}){return <div>{rows.length?rows.map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',padding:'10px 0',borderBottom:'1px solid #202938'}}>{r.map((x,j)=><span key={j} style={{textAlign:j?'right':'left',color:j===2?'#9aa6b8':'inherit'}}>{x}</span>)}</div>):<div style={{color:'#7f8b9c'}}>Нет средств</div>}</div>}
