'use client';
import { useState } from 'react';
import TradingChart from '../src/components/TradingChart';

const pairs=['BTCUSDT','ETHUSDT','BNBUSDT','XRPUSDT','SOLUSDT','TRXUSDT','DOGEUSDT','ADAUSDT','BCHUSDT','XMRUSDT','LINKUSDT','XLMUSDT','LTCUSDT','HBARUSDT','AVAXUSDT','SHIBUSDT','SUIUSDT','TONUSDT','DOTUSDT','UNIUSDT'];
const frames=['1m','5m','15m','1h','4h','1d'] as const;

export default function Home(){
 const [market,setMarket]=useState<'spot'|'futures'>('spot'); const [symbol,setSymbol]=useState('BTCUSDT'); const [frame,setFrame]=useState<typeof frames[number]>('1h');
 return <div className="app"><aside className="nav"><div className="brand">Финансы и инвестиция</div>{['Dashboard','Ledgers','Счета','Операции','Spot','Futures','Проекты','Расходы','Отчеты','Audit'].map(x=><a className={(market==='spot'&&x==='Spot')||(market==='futures'&&x==='Futures')?'active':''} key={x} onClick={()=>x==='Spot'?setMarket('spot'):x==='Futures'&&setMarket('futures')}>{x}</a>)}</aside>
 <main className="main"><div className="top"><div className="title">{market==='spot'?'Spot':'Futures'} · {symbol}</div><div className="live">● LIVE MARKET DATA</div></div>
 <div className="workspace"><section className="panel"><div className="panelTitle">Рынок</div>{pairs.map(p=><div key={p} className={'watch '+(p===symbol?'selected':'')} onClick={()=>setSymbol(p)}><span>{p.replace('USDT','')}</span><span className="muted">/USDT</span></div>)}</section>
 <section className="panel"><MarketHeader market={market} symbol={symbol}/><div className="toolbar">{frames.map(f=><button key={f} className={frame===f?'active':''} onClick={()=>setFrame(f)}>{f}</button>)}</div><TradingChart market={market} symbol={symbol} interval={frame}/></section>
 <section className="panel tradePanel"><div className="tabs"><button className={market==='spot'?'active':''} onClick={()=>setMarket('spot')}>Spot</button><button className={market==='futures'?'active':''} onClick={()=>setMarket('futures')}>Futures</button></div><ManualForm market={market} symbol={symbol}/></section></div></main></div>
}

function MarketHeader({market,symbol}:{market:'spot'|'futures',symbol:string}){return <div className="marketHeader"><div className="metric"><span className="muted">Пара</span><strong>{symbol}</strong></div><div className="metric"><span className="muted">Цена</span><strong id="last-price">—</strong></div><div className="metric"><span className="muted">24h</span><strong id="change-24">—</strong></div><div className="metric"><span className="muted">High / Low</span><strong id="high-low">—</strong></div><div className="metric"><span className="muted">Рынок</span><strong>{market.toUpperCase()}</strong></div></div>}

function ManualForm({market,symbol}:{market:'spot'|'futures',symbol:string}){return <div className="form"><div className="panelTitle" style={{margin:'-14px -14px 10px'}}>Добавить сделку вручную</div><label>Ledger</label><select><option>Выберите Ledger</option></select><label>Счет биржи</label><select><option>Выберите счет</option></select>{market==='spot'?<><label>Операция</label><select><option>BUY</option><option>SELL</option></select></>:<><div className="row"><div><label>Позиция</label><select><option>LONG</option><option>SHORT</option></select></div><div><label>Маржа</label><select><option>ISOLATED</option><option>CROSS</option></select></div></div><label>Плечо</label><input type="number" defaultValue="1" min="1"/></>}<label>Пара</label><input value={symbol} readOnly/><div className="row"><div><label>Количество</label><input type="number" placeholder="0.00"/></div><div><label>Цена</label><input type="number" placeholder="Текущая"/></div></div><label>Комиссия</label><input type="number" placeholder="0.00"/><label>Комментарий</label><input placeholder="Примечание"/><button className="primary">Сохранить сделку</button><div className="notice">Рыночные данные не создают учетных движений. Сделка будет записана только после ручного подтверждения.</div></div>}
